export type Region = "US" | "IN" | "CN";

export const REGION_CONFIG: Record<Region, { label: string; language: string; locale: string }> = {
  US: { label: "United States", language: "English", locale: "en-US" },
  IN: { label: "India", language: "Hindi", locale: "hi-IN" },
  CN: { label: "China", language: "Mandarin", locale: "zh-CN" },
};

export type SessionStatus =
  | "chatting"
  | "script_approved"
  | "keyframes_review"
  | "keyframes_approved"
  | "generating"
  | "done"
  | "failed";

export type Beat = {
  index: number;
  label: string;
  description: string;
  spokenLine: string;
  durationSec: number;
};

export type StructuredBrief = {
  product: string;
  brandName: string;
  targetAudience: string;
  tone: string;
  offer: string;
  visualStyle: string;
  beats: Beat[];
  localizedScripts: Record<Region, { lines: string[] }>;
};

export type ChatMessage = {
  id: string;
  role: "user" | "assistant" | "system";
  content: string;
  imageUrl?: string | null;
  createdAt: string;
};

// ---------------------------------------------------------------------------
// Brief type (full production spec generated at script approval)
// ---------------------------------------------------------------------------

export type CastMember = {
  role: string;
  description: string;
  age_range: string;
  gender: string;
  wardrobe: string;
  demeanor: string;
};

export type SceneBreakdown = {
  scene_number: number;
  start_time: number;
  end_time: number;
  visual_description: string;
  on_screen_text: string;
  text_animation: string;
  dialogue?: {
    speaker: string;
    line: string;
    delivery_note: string;
  };
  camera: {
    shot_type: string;
    movement: string;
    transition_in: string;
  };
};

/** Full production brief generated by Gemini at script approval. */
export type Brief = {
  client: {
    brand_name: string;
    industry: string;
    brand_guidelines_url?: string;
    logo_assets_url?: string[];
    existing_ad_references?: string[];
    competitor_references?: string[];
  };
  product: {
    name: string;
    category: string;
    tagline?: string;
    usp: string;
    price_point?: string;
    key_features: string[];
    product_assets?: {
      images_url?: string[];
      packshot_url?: string;
    };
  };
  campaign: {
    goal: string;
    kpi?: string;
    offer: {
      has_offer: boolean;
      offer_text?: string;
      promo_code?: string;
    };
    cta: {
      text: string;
      url?: string;
    };
  };
  target_cohort: {
    user_intent: string;
    demographics: {
      age_range: { min: number; max: number };
      gender: string;
      locations: string[];
      languages: string[];
    };
    psychographics: {
      interests: string[];
      behaviors: string[];
      pain_points: string[];
      lifestyle: string;
      values: string[];
    };
    device_preference: string;
  };
  delivery: {
    platforms: string[];
    aspect_ratios: string[];
    resolution: string;
    fps: number;
  };
  creative_direction: {
    overall_theme: string;
    mood: string;
    tone: string;
    visual_style: string;
    pacing: string;
    the_hook: {
      type: string;
      content: string;
      audio_element: string;
    };
    mandatory_inclusions: string[];
    strict_exclusions: string[];
  };
  color_palette: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    text_color: string;
  };
  typography: {
    primary_font: string;
    secondary_font: string;
  };
  script: {
    duration_seconds: number;
    scene_breakdown: SceneBreakdown[];
    end_card: {
      duration_seconds: number;
      logo_placement: string;
      text: string;
      cta_button: boolean;
    };
  };
  characters: {
    talent_type: string;
    cast: CastMember[];
  };
  audio: {
    voiceover: {
      enabled: boolean;
      gender?: string;
      tone?: string;
      accent?: string;
      script?: string;
    };
    music: {
      style: string;
      tempo: string;
      mood: string;
    };
  };
  localization: {
    versions_needed: {
      language: string;
      locale: string;
      adapted_script: string;
      cultural_notes: string;
    }[];
  };
};

